### ISSUE TITLE
High memory usage on FreePascal compiler versions (out of memory) - DAEMON

### ISSUE THREAD

**Issue by PascalCoinDev** [PascalCoinDev/PascalCoin#207]
PascalCoin was designed to work on a minimal hardware requeriments computer, for example a 1 GB RAM and single CPU computer.
For some unknown reason, FreePascal versions, use more memory than expected.
Same source code compiled using Delphi does not have this issue

## Compiler
FreePascal (all versions)

## Expected Behavior
Same memory usage than compiled with Delphi

## Current Behavior
Memory usage increases and does not reallocate/free properly

## Possible Solution
1. Check memory leaks that affects only when compiled with FreePascal?  (I think not)
2. Check how FreePascal uses Heap memory management? <-- Good way
3. Others...

**Comment by PascalCoinDev** [comment]
**USE_BIGBLOCKS_MEM_ON_DISK** directive is used in order to prevent a FreePascal issue with Heap allocation strategy that reuses big blocks of disposed memory and fragments it, this causes that when a new big block of same size that previously freeded mem is needed it will not reuse because has been fragmented...

Tested on FPC version 3.2.0 (2020-11-03) and order versions
Defragmention documented here: https://www.freepascal.org/docs-html/current/prog/progsu172.html
This issue is not detected on current Delphi memory manager (Tested on Delphi 10.3.2)

**FIXED** using USE_BIGBLOCKS_MEM_ON_DISK directive that activates TPCTemporalFileStream usage instead of TBytes (memory) usage

**Comment by SkybuckFlying** [comment]
The title is less than ideal. I read it as meaning the free pascal compiler itself crashes because of out of memory, which would be a bit weird but possibly.

However reading further into this, this does not seem to be the case and PascalCoin itself is experiencing high memory usage when compiled with Free Pascal.

This is probably caused by the memory manager, RTL (runtime library of free pascal). I don't know exact cause but seems to have something to do with big blocks and memory fragmentation. This same issue could also occur with the Delphi RTL.

So my advise to PascalCoin is to watch out with large memory block allocations or this issue may return !

Perhaps the memory manager of free pascal is affected sooner than that of Delphi. Not exactly sure.

I appreciate being alerted by this though. Quite interesting how a different memory manager/algorith might cause problematic behaviour depending on which compiler/rtl is being used.

Perhaps at the time of filing this report it was not known what was causing the problem but still.

Better title description might be:

PascalCoin runs out of memory on free pascal versions.

Bye for now,
  Skybuck.

**Comment by HermanSchoenfeld** [comment]
Hi SkybuckFlying, PascalCoin is in dire need of experienced developers such as yourself. Is there any way you could join this project and contribute? There are quite a few things that need attention and I'm sure you have ideas. If you wanted to re-join our Discord so we can resume and resolve where we last left off, please feel free.

**Comment by PascalCoinDev** [comment]
Hi Skybuck

Yes, perhaps my english tittle for this fixed issue is not good.
As you explained, yes, a different memory manager/algorithm can cause problematic behaviour depending on which compiler is used.

Also, take note, I recommend to use "Free Pascal" for core compilations (for example, as a service or daemon)
Delphi is good for GUI wallets, but for pure MIT projects is better to use FreePascal

This is why I usually make all compatible between FreePascal - Delphi
