### ISSUE TITLE
Feature: Add "Pay To Key" operation 

### ISSUE THREAD

**Issue by HermanSchoenfeld** [PascalCoinDev/PascalCoin#28]
One of the issues with PascalCoin is new users requiring to buy a PASA account before receiving PASC.

This request proposes a new operation type that allows a new user of PASC to "withdraw money to a public key"  which results in them being assigned a new account with that public key and those funds inside it via single operation. This makes process of adoption easier.

Add a new operation type called “Pay to Key” that works as follows:

1. Account A transfers X quantity to **public key** P 

2. When miner is minting a block and including the transaction (1)
  A. Miner can assign P to one of the generated accounts B **OR**
  B. Miner can assign P to an existing empty account B owned by miner
  C. Operation transfers X quantity from account A into account B  
  D. All nodes must verify A, B & C executed correctly by miner or reject block

3. When block accepted, the owner of public key P receives a client-side notification **_“Account B Assigned To You”_**

4. Users need to pay a very high fee for this transaction (cost of 1 PASA + network fee)

5. If operation not accepted in 1 hour, remove from mempool (becomes stale, fee too low)

**Economic Benefits:**

A - Mining becomes more lucrative since miners they now sell their generated accounts on-the-fly, resulting in higher ROI than other coins.

B - Will attract new miners that not only make network more secure, but break Nanopool's current mining monopoly.

**Comment by KunNw0n** [comment]
didnt get it. Account A pays the _cost of 1 PASA + network fee_ to the miner for an "abstract" new account ? But cost of 1 PASA couldnt be rated without open market. Even though net cost is 20 PASC, addy like 7771111 could be sold for the quite higher price. As soon as operations processed by automate, the miner will have no chance to reserve higher valued addys not to be used in such transactions.
Such a TX must be targeted to the specific not mined yet account number
like a bid to the miner for this one account and miner could rate the bids collected and his own ask rate for account to make the deal at the moment the account created. lets say PASA futures trading
Op fee goes to miner any way, Account KEy Change operation logic remains the same (beneficiary pub key provided). Every miner wallet could be configured to use simple base ask price for new accounts or regexp based multilevel price logic.

**Comment by HermanSchoenfeld** [comment]
KunnW0n - I've clarified text in issue so it makes more sense.

**Comment by KunNw0n** [comment]
Well, the thing is that _miner is minting a block and including the transaction_ is an automated procedure, though there must be some deterministic but yet configurable scenario to process a Pay To Key transaction without manual control from miner side. Means "Miner can assign P" must be automated.
Manual Pay To Key operation execution impossible because of following conditions:
1. There is no guarantee miner to take current bunch of pending operations (depends on chance to find the block)
2. All pending operations must be 100% ready to be applied to ledger at the moment the block found.
3. If some miner M1 choose to assign P to one of owned accounts, some where in the network miner M2 could do the same for one of M2s accounts. And race condition will be solved by the PoW consensus. But this means that miner wallet will hold custom (manually assigned to some target account) pending operations which could not be sent to the network until new block mined. This is a new wallet and protocol entity - _custom, not shareable pending operation_. We have no such entities for now.

So, there must be configurable processing rules in a miner's wallet allowing to find (preferably optimum) solution of task: haw to map existing pending PTK operations to the set of accounts "for sale" including potentially mined, taking an arguments with _fee offered_, _account address_ (pattern), _account history_ (brand new or used one), _miner ASK price_ for account if set.
