### ISSUE TITLE
Access Violation in PascalCoinWallet.exe Build 1.5.6

### ISSUE THREAD

**Issue by aclymer** [PascalCoinDev/PascalCoin#33]
I attempted to "Close" the wallet from the FileMenu because it said "NO BLOCKCHAIN" and "Obtaining valid blockchain". I had already restarted it once because it seemed to not be connecting to the network.

This time when I closed it I got an infinite loop of "Access violation at address 005608EE" messages and had to force quit from the task manager.
![image](https://user-images.githubusercontent.com/6611115/27187583-d6273454-51a8-11e7-9b38-2e78554bbebb.png)
![image](https://user-images.githubusercontent.com/6611115/27187734-3025fefe-51a9-11e7-8fd7-8ae1a6d0f9df.png)

Restarted Computer and tried again:
![image](https://user-images.githubusercontent.com/6611115/27189175-cdb58b7c-51ad-11e7-920d-cc2c4f675c06.png)

**Comment by creativechain-git** [comment]
Hi Aaron, I guess you are sending the message to a wrong mail address. We are Creativechain and our coin is Creativecoin (CREA) and not PascalCoin. You can get our wallet in: www.binaries.creativechain.net/latestBest regards,Creativechain Team
El 15 de junio de 2017 a las 16:58 Aaron Clymer <notifications@github.com> escribió:I attempted to "Close" the wallet from the FileMenu because it said "NO BLOCKCHAIN" and "Obtaining valid blockchain". I had already restarted it once because it seemed to not be connecting to the network.
This time when I closed it I got an infinite loop of "Access violation at address 005608EE" messages and had to force quit from the task manager.

**Comment by PascalCoinDev** [comment]
Please upgrade to V2.
Many bugs fixed. Thanks
