### ISSUE TITLE
Hangs up after hard fork

### ISSUE THREAD

**Issue by natugle** [PascalCoinDev/PascalCoin#39]
Perhaps there is a bug under Linux or Lazarus/FPC .
Both wallet and daemon hang up after block 115000 - but in nodes status it says Found block 1150xx (wait until downloaded)

I have of course restarted both wallet and daemon - even recompiled them. I have also downloaded a new blockchain and the precompiled wallet from Sourceforge. Nothing helps

Mint 18.1 Lazarus 1.5.4 and FPC 3.0.2.

**Comment by aclymer** [comment]
I have the same issue as @natugle

**Comment by ghost** [comment]
Delete data folder, appparams and block.log. Re-sync and should be good. Worked for me.

**Comment by HermanSchoenfeld** [comment]
Please do not delete /Data folder if you need to keep a history of operations (for exchanges, wallet providers, etc).

If you delete /Data, you will receive a Checkpoint in subsequent re-sync which will not contain historical operations.

**Comment by HermanSchoenfeld** [comment]
This issue is being investigated and an update will be posted when available.

**Comment by HermanSchoenfeld** [comment]
**HARD FORK INFORMATION**

Hard-fork was successful and went smoothly for critical users such as miners and exchanges. There were no bugs or crashes, however, many nodes experienced an issue described below. For those affected nodes, the solution is very simple:

1. Download latest build 2.1.1 and re-install

OR if you do not care about historical operations, you can just 

2. Delete your /Data sub-dir and restart wallet, you will be synced in few minutes due to new checkpointing functionality. Make sure you do not delete WalletKeys.dat files.


**HOW ISSUE OCCURED**

1. PascalCoin 2.0.0 and 2.1.0 were shipped with a pre-packaged SafeBox to improve sync performance. This pre-packaged SafeBox included block 107187a

Moments after the package was created, Murphy's Law strikes as follows:

2. Nanopool orphans it’s 107187a with an operationally identical block 107187b except with a different Payload (they do this occasionally since Nanopool appears to be 3 independent pools operating under one umbrella).

3. Since the operations between 107187a and 107187b are the same they affected the account balances and keys exactly the same way. As a result, the V1 SafeBox hash was identical for both 107187a and 107187b.

4. When block 115001 reached, the V2 hashing algorithm activated and detected the difference between 107187a and 107187b. This occurs because V2 now includes the block header in the account segment sub-structures of the SafeBox, which affects the SafeBox hash. Since the Payloads were different, the nodes that contained 107187a hashed the SafeBox differently than those who had 107187b. 

5. Only nodes that installed using the pre-packaged installer were affected. All other nodes that synchronised from block 0, or who rebuilt their own SafeBox were unaffected.


**CONCLUSION**

A - Completely harmless. No funds were lost, stolen or changed whatsoever. We know this for a fact because if there was a difference in account balance or key ownership, step (3) would have detected this difference early on as the V1 SafeBox hash would have been different. 

B - Poloniex and other miners were not affected at all and are sending/receiving funds normally.

C - Thanks to V2 Checkpointing, we will no longer ship SafeBox’s inside the installer. This issue will never happen again.

Apologies for inconvenience, but this issue was harmless and we consider the V2 Hard-Fork a success nonetheless.
