### ISSUE TITLE
PIP-0007 Discussion - New Wallet GUI

### ISSUE THREAD

**Issue by HermanSchoenfeld** [PascalCoinDev/PascalCoin#47]

**Comment by SkybuckFlying** [comment]
1. Displaying the public key for each account could be usefull, especially if the public key is searchable. For example when users only know the public key but not the associated account number. This could be an extra column, Which could conventiently be re-sized or put in the back or disabled via a pop-up menu to select which columns to display.

This feature would require the grid to only load accounts into the grid for a certain range. Since converting public key's from binary to text takes a lot of computations.

(I would also like to see this feature in PascalCoin "current/complex" wallet.

2.  I would like to see the account number and account checksum code either seperated into seperate columns. Or the -10 removed. I assume the -10 is a checksum.

Currently it looks like it's displaying some kind of aggretiate... a range from 0 to 10.

So 0-10 looks like it means account range 0 to 10. This is very deceptive and confusing to new users ! And even experienced users !

("Current/Complex" wallet has same confusion too ! Would like to see a change there too.)

**Comment by Drosakis** [comment]
I believe it would also be a good idea to create an option that we choose minimization to tray or default standard minimization.
