### ISSUE TITLE
Wallet binaries?

### ISSUE THREAD

**Issue by Michal-Mikolas** [PascalCoinDev/PascalCoin#55]
Hello, 
I am quite good at computers (I'm web developer), but still I was not able to run basic PascalCode wallet on Linux. The process is too complicated and tricky for normal users. 

Do you plan to make any binaries? If yes, when? 
Without classic binaries, PascalCoin will be never used by the general public... 

I guess the same problem is the Windows version of wallet and the mining application as well.

**Comment by ghost** [comment]
hi Michal,
I mentioned this to the team and that also maybe the instructions need to be revised. I'm sure it can be frustrating since there are many steps. Have you tried the pre-compiled wallet here - https://sourceforge.net/projects/pascalcoin/files/. If you are having issues, come join the slack channel for live help - http://www.pascalcoin.org/slack-self-invite/

**Comment by Michal-Mikolas** [comment]
Oh, thank you for the link. 

So I tried to download "PascalCoinWalletB2.1.2.0.exe" and install it via Wine. For the first look it works fine in Ubuntu :+1:
