### ISSUE TITLE
Where is the PascalCoinMiner?

### ISSUE THREAD

**Issue by gehnster** [PascalCoinDev/PascalCoin#57]
The solo miner doesn't seem to exist anymore. Your documents either reference it on sourceforge, isn't there, or you reference the Claymore dual miner but that only supports pools.

Please update your files/documentation with info on where the regular miner is!

**Comment by jstone3769** [comment]
I came here to say the same thing, the solo miner appears to be missing

**Comment by ghost** [comment]
Here is a link to download pascalproxyv3
https://github.com/Vorksholk/PascalCoin-CUDA/releases

**Comment by SkybuckFlying** [comment]
It's PascalCoinMiner.pp on github that's the source code which can be compiled with Lazarus.

If it's still update/working I am not sure. It's probably useless since all the big mining pools always win.

But you could try it out, a binary version + opencl kernel + batch file setup can be downloaded here:

http://www.skybuck.org/PascalCoin/PascalCoinMiner.zip

Please do change the nickname in the batchfile from Skybuck to something.

If it does work and you actually mined a block let me know ! ;) :)

(Otherwise I will test it out someday on a simulation/test net or something like that to see if it's still working/valid... but just a slow method.)
