### ISSUE TITLE
Confused how to even create an account

### ISSUE THREAD

**Issue by imkane** [PascalCoinDev/PascalCoin#59]
I have the Windows client. I'm trying to create my own account that has a 6-digit address so someone can send me some coins. The GUI is very confusing. I'd love some help :)

Thanks!

**Comment by ghost** [comment]
Hey! Come join the Discord for live help from the community: https://discord.gg/sJqcgtD

That being said, the key pair is not your account. PascalCoin works differently. You have to get an account through various means, but one is not generated in the wallet unless you are solo mining and find a block. It's easy to get a pascal account (PASA). Some cost 1 PASC, some cost 3 PASC and really nice numbers like 2552-18 cost 500 PASC (on pascwallet.com)

**Comment by SkybuckFlying** [comment]
Free (PascalCoin) accounts are temporarely being dispensed at:

https://telegram.me/pascalcoin 

It works as follows:

1. Open PascalCoin Wallet and click Project->Private keys. (Or hold Control-P)

2. (Input wallet password if wallet is locked, otherwise skip this step).

3. Generate a new key, change name to your Nickname or so.

4. Click export public key. (This will store the public key in clipboard).

5. Visit the telegram link and register, this will require a mobile phone number ! Input a mobile phone number and receive the sms. (Free SMS-ing services on the internet might also work for this).

6. Type /getpasa YourPublicKey.   (Paste the your public key from the clipboard) Press enter... make sure there are no spaces or return lines between /getpasa and public key. It must be online... this is a bit akward but try.

7. The bot will give you an account number. This is your PascalCoin account.

8. Go to PascalCount Account Explorer tab and click the checkbox called: "explore accounts with one of my  Wallet Keys". Check if current block age is lower than 20 minutes or so. If your account number shows up 
below in the account grid/account explorer then your private/public key pair is now attached to that account so it is yours !

Good luck and happy PascalCoining ! =D

**Comment by ankemist** [comment]
step 6 does not work. 

 /getpasa3GhhbonRrStc2jESrs8nSEywSyRZ7sWdxNiUCchNKwBhHwMHVvUxFHPbrX8rFxjx5CdqXtiSRARp

[10:22:37 PM] BitBot:
This command has not been recognised.

**Comment by ghost** [comment]
It works if you separate the command from the key, like so: 
/getpasa 3GhhbonRrStc2jESrs8nSEywSyRZ7sWdxNiUCchNKwBhHwMHVvUxFHPbrX8rFxjx5CdqXtiSRARp

**Comment by ankemist** [comment]
Well, tried 
/getpasa PublicKey 
that didn't work.  someone at Pascalcoin suggested:
/getpasa@pascalcoinofficial PublicKey 
it didn't work neither.  The bot replied "This command has not been recognised."
anyway, I will try to mine another coin to buy a Pasc account.  Thanks a lot for all your help!

**Comment by ghost** [comment]
Just type /getpasa paste pub key. It’s really not hard.

**Comment by ankemist** [comment]
OK.  it worked.  Thanks a lot for all your help!  It worked this way, at the PASCALCOIN forum, click @pascalcoinofficial and join the official forum where the /getpasa command worked there for now.  The officials said that there are only around 50 free PASC accounts left there.

**Comment by SkybuckFlying** [comment]
Your idea to leave out the space is pretty cool ! That would make it a bit easier if the bot could recgonize that ! :) The space requirement is annoying as hell ! ;) :) Not sure if it will make things better though... the newline character is also annoying as hell if it were to be between getpasa<-->public... 
(It's probably so annoying because the keys are so long... and the chat bar so small in telegram... at least that's how I experienced it ! ;) the key tends to fall off these screen... less observant people might not notice or understand the problem if there is a newline after the space.)
well anyway glad you succeeded, great to see people help each other ! Love it ! =D

**Comment by onikstewart** [comment]
How do I get a Pascal wallet? Please help.

**Comment by ghost** [comment]
Get a free account in Discord

https://discord.gg/sJqcgtD

**Comment by EDToaster** [comment]
If you join the official pascalcoin discord server, you can get a free wallet account. Just ask around.

**Comment by Michal-Mikolas** [comment]
Why can't we just register account from the PascalCoin official wallet? Why to make simple things complicated? 

Please [KISS](https://en.wikipedia.org/wiki/KISS_principle) :-)

**Comment by HermanSchoenfeld** [comment]
Yes, this has been no 1 impediment to adoption and it's been solved in V6 (See https://github.com/PascalCoin/PascalCoin/blob/master/PIP/PIP-0041.md)

To get an account, you'll be able to send to addresses of the form:

@[1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2]

Which will buy an account in-protocol and send those funds to you, automatically. The account fee will be determined by a block policy. There will be millions of floating accounts for new users.

**Comment by Michal-Mikolas** [comment]
I don't really understand... 

I have opened my PascalCoin Wallet (installed yesterday on Windows). 

- What are the steps necesery to _"send to addresses of the form"_ ?
- Which _"form"_ ? 
- I don't have any coins so I can't send them anywhere. I don't even have an account. Or should I send something else then coins to _"the form"_ ? 

This still seems very confusing. Newbies need buttons like _"Create free acount"_ and _"Purchase paid account"_ buttons right in the application.
